//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutrirSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartaoCredito
    {
        public decimal Id { get; set; }
        public int Bandeira { get; set; }
        public string Titular { get; set; }
        public decimal numParc { get; set; }
        public decimal valorParc { get; set; }
    
        public virtual Pagamento Pagamento { get; set; }
    }
}
