//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutrirSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public decimal idConsulta { get; set; }
        public Nullable<int> statusConsulta { get; set; }
        public Nullable<int> tipoConsulta { get; set; }
        public System.DateTime DataHora { get; set; }
        public decimal Paciente_cpf { get; set; }
        public decimal Funcionario_cpf { get; set; }
        public decimal MedidasCorporais_idMedidasCorporais { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Funcionario Funcionario { get; set; }
        public virtual Pagamento Pagamento { get; set; }
        public virtual MedidasCorporais MedidasCorporais { get; set; }
    }
}
