//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutrirSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convenio
    {
        public Convenio()
        {
            this.Paciente = new HashSet<Paciente>();
        }
    
        public decimal numPlano { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<Paciente> Paciente { get; set; }
    }
}
