//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutrirSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dieta
    {
        public Dieta()
        {
            this.Paciente = new HashSet<Paciente>();
            this.ProdutosClinica = new HashSet<ProdutosClinica>();
        }
    
        public decimal idDieta { get; set; }
        public string dieta1 { get; set; }
    
        public virtual ICollection<Paciente> Paciente { get; set; }
        public virtual ICollection<ProdutosClinica> ProdutosClinica { get; set; }
    }
}
