//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutrirSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedidasCorporais
    {
        public decimal idMedidasCorporais { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> imc { get; set; }
        public Nullable<double> altura { get; set; }
        public Nullable<double> massaMagra { get; set; }
        public Nullable<double> percGordura { get; set; }
        public Nullable<double> glicemia { get; set; }
    }
}
