//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutrirSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Consulta = new HashSet<Consulta>();
            this.Convenio = new HashSet<Convenio>();
        }
    
        public decimal idPaciente { get; set; }
        public string objetivo { get; set; }
        public string esportesPraticados { get; set; }
        public int tipoSanguineo { get; set; }
        public decimal cpf { get; set; }
        public decimal Dieta { get; set; }
        public decimal Habitos { get; set; }
    
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual ICollection<Convenio> Convenio { get; set; }
        public virtual Dieta Dieta1 { get; set; }
        public virtual Habitos Habitos1 { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
