//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutrirSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente : Pessoa
    {
        public Paciente()
        {
            this.Consulta = new HashSet<Consulta>();
        }
    
        public string objetivo { get; set; }
        public string esportesPraticados { get; set; }
        public int tipoSanguineo { get; set; }
        public string descHabitosEsp { get; set; }
        public string descHabitosAli { get; set; }
    
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual Dieta Dieta { get; set; }
        public virtual Convenio Convenio { get; set; }
    }
}
