//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutrirSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public decimal idPagamento { get; set; }
        public decimal valor { get; set; }
        public int formaPagamento { get; set; }
        public int statusPagamento { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual CartaoCredito CartaoCredito { get; set; }
        public virtual Consulta Consulta { get; set; }
    }
}
