//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutrirSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public Pessoa()
        {
            this.Funcionario = new HashSet<Funcionario>();
            this.Paciente = new HashSet<Paciente>();
        }
    
        public decimal cpf { get; set; }
        public string nome { get; set; }
        public string rua { get; set; }
        public decimal numero { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public int sexo { get; set; }
        public string email { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public string telefone { get; set; }
        public string celular { get; set; }
        public string apelido { get; set; }
    
        public virtual ICollection<Funcionario> Funcionario { get; set; }
        public virtual ICollection<Paciente> Paciente { get; set; }
    }
}
