//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutrirSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutosClinica
    {
        public ProdutosClinica()
        {
            this.Dieta = new HashSet<Dieta>();
        }
    
        public decimal idProdutosClinica { get; set; }
        public string nome { get; set; }
        public string gordura { get; set; }
        public string carboidratos { get; set; }
        public string fibra { get; set; }
        public string sodio { get; set; }
    
        public virtual ICollection<Dieta> Dieta { get; set; }
    }
}
